name: main
on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches: [ master ]

jobs:
  extract_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Install dependencies
        run: npm i -g jsdoc && npm install jsdoc-json

      - name: pull eris repo
        run: git clone https://github.com/abalabahaha/eris 

      - name: generate docs
        run: jsdoc --template ./node_modules/jsdoc-json --destination docs.json eris/lib/Client.js && rm -rf out && rm -rf node_modules
        
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || git commit -m "feat: update json" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
